#!/usr/bin/env bash

declare -a AWS_CLI_OPTS=()
declare -i ALL_FOR_AWS_CLI=0

parse_args() {
    while [[ $# -gt 0 ]]; do
        key="$1"
        case $key in
        -h|--help)
            echo "Watch Amazon SageMaker Notebook instance."
            echo "Usage: $(basename ${BASH_SOURCE[0]}) <NB_NAME> --awscli-arg=val -- --awscli-arg val"
            exit 0
            ;;
        --)
            # Anything after this means "--option value"
            ALL_FOR_AWS_CLI=1
            shift
            ;;
        -*)
            # This takes care "--option=value"
            AWS_CLI_OPTS+=($key)
            shift
            ;;
        *)
            [[ ${ALL_FOR_AWS_CLI} > 0 ]] && AWS_CLI_OPTS+=($key) || NB_NAME=$key
            shift
            ;;
        esac
    done
}

parse_args "$@"
[[ "${NB_NAME}" == "" ]] && exit 0

cmd="aws ${AWS_CLI_OPTS[@]} sagemaker describe-notebook-instance --notebook-instance-name ${NB_NAME} | egrep --color=always '^.*NotebookInstanceStatus.*$|$'"
watch --color -n 30 "${cmd}"
